// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Categories
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

// Packs
export const FETCH_PACKS_SUCCESS = 'FETCH_PACKS_SUCCESS';
export const SAVE_PACK_SUCCESS = 'SAVE_PACK_SUCCESS';
export const DELETE_PACK_SUCCESS = 'DELETE_PACK_SUCCESS';

// Game state
